version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fastapi-app
    ports:
      - "8000:80"
    networks:
      - app-network
    environment:
        - POSTGRES_HOST=postgres
        - POSTGRES_PORT=5432
        - POSTGRES_DB=powerfi
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: angular-app
    ports:
      - "4200:80"
    networks:
      - app-network
    depends_on:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: powerfi
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data:
